//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activosfijos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class activofijoEntities : DbContext
    {
        public activofijoEntities()
            : base("name=activofijoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<apreciacion> apreciacion { get; set; }
        public DbSet<bien> bien { get; set; }
        public DbSet<cargo> cargo { get; set; }
        public DbSet<categoria> categoria { get; set; }
        public DbSet<departamento> departamento { get; set; }
        public DbSet<depreciacion> depreciacion { get; set; }
        public DbSet<detalleapreciacion> detalleapreciacion { get; set; }
        public DbSet<detalledepreciacion> detalledepreciacion { get; set; }
        public DbSet<empleado> empleado { get; set; }
        public DbSet<gestion> gestion { get; set; }
        public DbSet<ingresoegreso> ingresoegreso { get; set; }
        public DbSet<mantenimiento> mantenimiento { get; set; }
        public DbSet<mantenimientobien> mantenimientobien { get; set; }
        public DbSet<moneda> moneda { get; set; }
        public DbSet<responsable> responsable { get; set; }
        public DbSet<revision> revision { get; set; }
        public DbSet<tipobien> tipobien { get; set; }
        public DbSet<tipocambio> tipocambio { get; set; }
    }
}
