//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activosfijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class apreciacion
    {
        public apreciacion()
        {
            this.detalleapreciacion = new HashSet<detalleapreciacion>();
        }
    
        public int idapreciacion { get; set; }
        public double porcentajeapreciacion { get; set; }
    
        public virtual ICollection<detalleapreciacion> detalleapreciacion { get; set; }
    }
}
