//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activosfijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bien
    {
        public bien()
        {
            this.mantenimientobien = new HashSet<mantenimientobien>();
            this.responsable = new HashSet<responsable>();
            this.revision = new HashSet<revision>();
        }
    
        public int idbien { get; set; }
        public string nombre { get; set; }
        public double preciocompra { get; set; }
        public double precioactual { get; set; }
        public Nullable<int> idingreso { get; set; }
        public int idtipobien { get; set; }
        public Nullable<System.DateTime> fechaingreso { get; set; }
        public Nullable<System.DateTime> fechaegreso { get; set; }
        public Nullable<int> idegreso { get; set; }
    
        public virtual ingresoegreso ingresoegreso { get; set; }
        public virtual ingresoegreso ingresoegreso1 { get; set; }
        public virtual tipobien tipobien { get; set; }
        public virtual ICollection<mantenimientobien> mantenimientobien { get; set; }
        public virtual ICollection<responsable> responsable { get; set; }
        public virtual ICollection<revision> revision { get; set; }
    }
}
