//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activosfijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class depreciacion
    {
        public depreciacion()
        {
            this.detalledepreciacion = new HashSet<detalledepreciacion>();
        }
    
        public int iddepreciacion { get; set; }
        public double porcentajedepreciacion { get; set; }
    
        public virtual ICollection<detalledepreciacion> detalledepreciacion { get; set; }
    }
}
