//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activosfijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public empleado()
        {
            this.responsable = new HashSet<responsable>();
            this.revision = new HashSet<revision>();
        }
    
        public int idempleado { get; set; }
        public int idcargo { get; set; }
        public int iddepartamento { get; set; }
        public string nombre { get; set; }
        public int ci { get; set; }
        public string direccion { get; set; }
    
        public virtual cargo cargo { get; set; }
        public virtual departamento departamento { get; set; }
        public virtual ICollection<responsable> responsable { get; set; }
        public virtual ICollection<revision> revision { get; set; }
    }
}
