//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activosfijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gestion
    {
        public gestion()
        {
            this.detalleapreciacion = new HashSet<detalleapreciacion>();
            this.detalledepreciacion = new HashSet<detalledepreciacion>();
            this.revision = new HashSet<revision>();
            this.tipocambio = new HashSet<tipocambio>();
        }
    
        public int idgestion { get; set; }
        public System.DateTime fecha { get; set; }
    
        public virtual ICollection<detalleapreciacion> detalleapreciacion { get; set; }
        public virtual ICollection<detalledepreciacion> detalledepreciacion { get; set; }
        public virtual ICollection<revision> revision { get; set; }
        public virtual ICollection<tipocambio> tipocambio { get; set; }
    }
}
