//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activosfijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ingresoegreso
    {
        public ingresoegreso()
        {
            this.bien = new HashSet<bien>();
            this.bien1 = new HashSet<bien>();
        }
    
        public int idingresoegreso { get; set; }
        public string tipoingreso { get; set; }
        public string tipoegreso { get; set; }
    
        public virtual ICollection<bien> bien { get; set; }
        public virtual ICollection<bien> bien1 { get; set; }
    }
}
