//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activosfijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mantenimientobien
    {
        public int idmantenimientobien { get; set; }
        public int idbien { get; set; }
        public int idmantenimiento { get; set; }
        public string descripcion { get; set; }
    
        public virtual bien bien { get; set; }
        public virtual mantenimiento mantenimiento { get; set; }
    }
}
