//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activosfijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipocambio
    {
        public int idtipobien { get; set; }
        public int idgestion { get; set; }
        public int idmoneda { get; set; }
    
        public virtual gestion gestion { get; set; }
        public virtual moneda moneda { get; set; }
    }
}
