//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Activosfijos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipobien
    {
        public tipobien()
        {
            this.bien = new HashSet<bien>();
            this.detalleapreciacion = new HashSet<detalleapreciacion>();
            this.detalledepreciacion = new HashSet<detalledepreciacion>();
        }
    
        public int idtipobien { get; set; }
        public string descripcion { get; set; }
        public int idcategoria { get; set; }
    
        public virtual ICollection<bien> bien { get; set; }
        public virtual categoria categoria { get; set; }
        public virtual ICollection<detalleapreciacion> detalleapreciacion { get; set; }
        public virtual ICollection<detalledepreciacion> detalledepreciacion { get; set; }
    }
}
